site_name: 'GanttProject Docs'
site_description: 'Assorted bits of GanttProject Documentation'
site_author: 'BarD Software s.r.o'
site_url: 'http://docs.ganttproject.biz'

theme:
  name: 'material'
  palette:
    primary: '#616161'
    accent: orange

copyright: 'Copyright &copy; 2018 - 2020 BarD Software s.r.o'

nav:
  - 'For End Users': 'user/index.md'
  - 'For Developers': 'development/index.md'
  - Releases: 'releases/index.md'
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/bardsoftware/ganttproject'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/ganttproject'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://facebook.com/ganttproject'

# Google Analytics
google_analytics:
  - 'UA-1173427-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
